### ISSUE TITLE
Output referrer to help diagnose crawl errors

### ISSUE THREAD

**Issue by exortech** [cloudfour/lighthouse-parade#126]
Simplecrawler does find and attempt to crawl a lot of invalid uris - especially in script tags. However, it does occasionally find useful broken links. The current output of lighthouse-parade makes it difficult to determine which page contains the broken link. Including the referrer (the page where the broken link was discovered) makes it much easier to identify where the broken link is.

**Comment by emilienbidet** [comment]
Maybe linked to #131

**Comment by calebeby** [comment]
Closing since https://github.com/cloudfour/lighthouse-parade/pull/128 was merged
