### ISSUE TITLE
Some HTTPS URLs fail

### ISSUE THREAD

**Issue by calebeby** [cloudfour/lighthouse-parade#24]
HTTPS URL:
```
> node dist/scan_task.js "https://www.dfwfreeways.com/"
Created CSV file
Starting the crawl...
Scan complete
Aggregating reports...
TypeError [ERR_STREAM_NULL_VALUES]: May not write null values to stream
```

HTTP URL:
```
> node dist/scan_task.js "http://www.dfwfreeways.com/"
Created CSV file
Starting the crawl...
Crawled http://www.dfwfreeways.com/ [text/html; charset=utf-8] (79176 bytes)
Report is done for http://www.dfwfreeways.com/
Wrote report for http://www.dfwfreeways.com/
```

@emersonthis said that it is probably an issue with the `www`, not with `https`

**Comment by emersonthis** [comment]
The HTTPS urls I've tested seem to work. And the error message above suggests to me that the crawler simply isn't finding anything and then trying to write non-existent data. So my hunch is that the subdomain is more the issue here. I know simplecrawler has configurations that tell it how strict to be about subdomains. I think this is where we should start troubleshooting this.

**Comment by emersonthis** [comment]
The simplecrawler configuration docs are here: https://github.com/simplecrawler/simplecrawler#configuration
I'd start by looking at `crawler.scanSubdomains` and `crawler.ignoreWWWDomain` and `crawler.stripWWWDomain`. (The docs don't say what the default values are, so we may want to do some initial fiddling to better understand what the crawler is doing now)

Side note: If I'm even vaguely correct about the nature of this problem, we definitely want better/clearer error handling here. Ex: `console.log('No pages were found. Please check that the URL is correct and the use of www is correct' )`

**Comment by calebeby** [comment]
@emersonthis I tried `crawler.scanSubdomains = true` and I also tried all 4 combinations of `ignoreWWWDomain` and `stripWWWDomain`. In all the cases I got the same result, the `https` url is not working 😕
