### ISSUE TITLE
Make it an installable CLI instead of a repo that you clone

### ISSUE THREAD

**Issue by calebeby** [cloudfour/lighthouse-parade#25]
It would be nice to be able to run:

```
npx lighthouse-parade scan ...
```

to get it installed/running instead of cloning the repo.

This requires:
- [x] Adding a CLI entrypoint script that figures out which subcommand is requested
- [x] Adding `bin` to `package.json`
- [ ] Publishing to npm
- [ ] Document changeset/publish workflow

**Comment by emersonthis** [comment]
This is a good idea, but I want to sidestep the associated overhead of publishing releases to npm (for now) until the codebase is a bit more stable. Then we should definitely do this.

**Comment by calebeby** [comment]
Reopened since we still need to publish to npm
