### ISSUE TITLE
Add test for error message when no pages are found

### ISSUE THREAD

**Issue by calebeby** [cloudfour/lighthouse-parade#31]
https://github.com/cloudfour/lighthouse-parade/pull/30#issuecomment-700145996

> ```js
> import { scan } from './scan-task'
> test('Displays useful error if no pages are found while crawling', () => {
>   const result = await scan('https://nonexistent-website.com')
>   expect(result.error).toMatch(/No pages were found for this site/)
> })
> ```

> We can get away with it for this test, but it's hacky for tests to make live requests. Also very slow. Sooner than later we need to figure out a way to do this the right way. So maybe we take our time with that future issue when we get there.

**Comment by emersonthis** [comment]
@calebeby  how do you feel about taking this on?

**Comment by calebeby** [comment]
Sounds good, I'll start on this soon.

**Comment by emersonthis** [comment]
Cool. Take your time with this. I see this one as much about figuring out the underlying test strategy for mocking/stubbing live lighthouse requests.

**Comment by calebeby** [comment]
@emersonthis If I understand correctly we'll only need to stub the requests from the crawler, not from lighthouse, right?

**Comment by emersonthis** [comment]
For this specific test, you're right. I'm trying to find excuses to start thinking/planning for how to run tests "around" lighthouse, too. Maybe here isn't the right place for that...

**Comment by calebeby** [comment]
I think we may end up needing a "lighthouse replacement" that we can use for testing in place of lighthouse, but I don't think this is the right issue for that either

**Comment by emersonthis** [comment]
I'll create a new issue...
