### ISSUE TITLE
Convert to TypeScript

### ISSUE THREAD

**Issue by emersonthis** [cloudfour/lighthouse-parade#4]
- [x] Set up TS https://github.com/cloudfour/lighthouse-parade/pull/11
- [x] Convert to TS: `utilities` https://github.com/cloudfour/lighthouse-parade/pull/15
- [x] Convert to TS: `reportToRow` https://github.com/cloudfour/lighthouse-parade/pull/17
- [x] Convert to TS: `combine` https://github.com/cloudfour/lighthouse-parade/pull/19
- [ ] Convert to TS: `combine_task` https://github.com/cloudfour/lighthouse-parade/pull/23
- [x] Convert to TS: `lighthouse` https://github.com/cloudfour/lighthouse-parade/pull/20
- [ ] Convert to TS: `lighthouse_task` https://github.com/cloudfour/lighthouse-parade/pull/23
- [x] Convert to TS: `url_csv_maker` https://github.com/cloudfour/lighthouse-parade/pull/22
- [ ] Convert to TS: `scan_task` https://github.com/cloudfour/lighthouse-parade/pull/23
- [ ] Convert to TS: `urls_task` https://github.com/cloudfour/lighthouse-parade/pull/23

**Comment by emersonthis** [comment]
Closed by #11

**Comment by calebeby** [comment]
@emersonthis I think we should leave this open till we get all the individual files converted to having types

**Comment by emersonthis** [comment]
@calebeby Ok. When you have a chance, can you add a checklist to the description so it's more obvious at a glance that this is in progress.
