### ISSUE TITLE
Are lighthouse reports running concurrently?

### ISSUE THREAD

**Issue by emersonthis** [cloudfour/lighthouse-parade#5]
- [x] Are lighthouse reports running concurrently?
  -> No, they are not currently
- [ ] Should they be?

Running lighthouse reports concurrently can be problematic for two reasons:
1. Multiple instances in a single thread is unreliable and will error (often). This is solved with child processes. However...
2. Even in child processes, multiple lighthouses running concurrently may run into hardware resource limitations that skew the results. <-- these tolerances are not well understood yet.

If you look at scan_task.js:32 you see that at the moment, we `await` the results from a lighthouse report, but the function is invoked inside an event callback that might be firing concurrently. This isn't evident from the output we see in the console, but we should figure out exactly what's going on. Then, we should decide if it is/isn't optimal. If there _is_ a responsible way to run multiple lighthouses concurrently, it would make the script run a _lot_ faster and that would be great.

**Comment by calebeby** [comment]
@emersonthis I think they are not running concurrently because we are using `spawnSync`, which will block our main thread until the lighthouse process finishes

**Comment by emersonthis** [comment]
Great. If/when you feel confident about this, please check the checkbox above. But feel free to leave this issue open until we have time to address the second question.

**Comment by calebeby** [comment]
@emersonthis Can we close this issue since we have #27?
